services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'htmx'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'pass'
    volumes:
      - mysql_data:/var/lib/mysql